export type AuditAction =
  | 'ACCOUNT_PROVISIONED'
  | 'ACCOUNT_RENAMED'
  | 'ACCOUNT_SUSPENDED'
  | 'ACCOUNT_CLOSED'
  | 'KYC_TIER_CHANGED'
  | 'MISDIRECTED_PAYMENT'
  | 'API_KEY_GENERATED'
  | 'ACCOUNT_REACTIVATED'
  | 'TRANSACTION_FLAGGED';
